version: 2.1

orbs:
  go: circleci/go@0.2.0


commands:
  get-coverage-tools:
    description: "Get coverage tools"
    steps:
      - run: go get -u github.com/schrej/godacov
      - run: go get -u github.com/haya14busa/goverage
  coverage:
    description: "Generate and upload coverage"
    steps:
      - goverage -v -coverprofile=coverage.out ./...
      - godacov -t $CODACY_PROJECT_TOKEN -r ./coverage.out -c $CIRCLE_SHA1

jobs:
  build:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - get-coverage-tools
      - go/save-cache
      - go/test
      - coverage
