version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4
      
    working_directory: /go/src/github.com/hassieswift621/discord-goflake
    
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results
      - run: gotestsum --junitfile /tmp/test-results/unit-tests.xml
      - store_test_results:
          path: /tmp/test-results
