version: 2
jobs:
  build:
    docker:
      - image: hassieswift621/circleci-go-codacy:1.12.5
      
    working_directory: /go/src/github.com/hassieswift621/discord-goflake
    
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results
      - run: gotestsum --junitfile /tmp/test-results/unit-tests.xml --format standard-verbose
      - store_test_results:
          path: /tmp/test-results
      - run: go get github.com/schrej/godacov
      - run: go test -coverprofile=coverage.out
      - run: godacov -t $CODACY -r ./coverage.out -c $CIRCLE_SHA1
      - run: go test -bench=.
